image: gitpod/workspace-full-vnc

tasks:
  - name: Start Apollo
    init: npm install --global @jbrowse/cli @apollo-annotation/cli
    command: docker compose up

ports:
  - port: 80
    onOpen: ignore

workspaceLocation: "/workspace"
